export const users = [
  {
    id: "1",
    name: "Alex Johnson",
    handle: "@alexj",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80",
    banner: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80",
    bio: "Documenting my favorite spots around the world. NYC 📍\nCoffee addict & museum goer.",
    isPrivate: false,
    followers: 1240,
    following: 342,
  },
  {
    id: "2",
    name: "Mia T.",
    handle: "@miatravels",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80",
    banner: "https://images.unsplash.com/photo-1502602898657-3e907a5ea0c1?auto=format&fit=crop&w=800&q=80",
    bio: "Travel enthusiast & food lover",
    isPrivate: false,
    followers: 5800,
    following: 120,
  },
  {
    id: "3",
    name: "David Kim",
    handle: "@dkim",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
    banner: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=80",
    bio: "",
    isPrivate: true,
    followers: 150,
    following: 200,
  },
  {
    id: "4",
    name: "Sarah Chen",
    handle: "@sarahexplores",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=150&q=80",
    banner: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80",
    bio: "Adventure seeker | Architecture lover | Based in London",
    isPrivate: false,
    followers: 3200,
    following: 890,
  },
  {
    id: "5",
    name: "Marcus Rodriguez",
    handle: "@marcuseats",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80",
    banner: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=80",
    bio: "Food critic & chef | Exploring culinary gems worldwide",
    isPrivate: false,
    followers: 8900,
    following: 450,
  },
  {
    id: "6",
    name: "Emma Williams",
    handle: "@emmawanders",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80",
    banner: "https://images.unsplash.com/photo-1517154421773-0529f29ea451?auto=format&fit=crop&w=800&q=80",
    bio: "Solo traveler ✈️ | Coffee enthusiast ☕",
    isPrivate: false,
    followers: 2100,
    following: 620,
  },
  {
    id: "7",
    name: "James Park",
    handle: "@jamesfinds",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80",
    banner: "https://images.unsplash.com/photo-1560969184-10fe8719e047?auto=format&fit=crop&w=800&q=80",
    bio: "Finding hidden gems in every city",
    isPrivate: false,
    followers: 4500,
    following: 1200,
  },
  {
    id: "8",
    name: "Olivia Martinez",
    handle: "@oliviaexplores",
    avatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=150&q=80",
    banner: "https://images.unsplash.com/photo-1534070249-34b748a9d18e?auto=format&fit=crop&w=800&q=80",
    bio: "Art & design curator | Museum lover",
    isPrivate: false,
    followers: 6700,
    following: 340,
  },
];

export const currentUser = users[0];

export const collections = [
  {
    id: "c1",
    userId: "1",
    title: "Tokyo 2024",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80",
    isPublic: true,
  },
  {
    id: "c2",
    userId: "1",
    title: "Local NYC Faves",
    coverImage: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=800&q=80",
    isPublic: true,
  },
  {
    id: "c3",
    userId: "2",
    title: "Paris Cafes",
    coverImage: "https://images.unsplash.com/photo-1502602898657-3e907a5ea0c1?auto=format&fit=crop&w=800&q=80",
    isPublic: true,
  },
  {
    id: "c4",
    userId: "4",
    title: "London Architecture",
    coverImage: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80",
    isPublic: true,
  },
  {
    id: "c5",
    userId: "5",
    title: "Barcelona Bites",
    coverImage: "https://images.unsplash.com/photo-1562883676-8c7feb83f09b?auto=format&fit=crop&w=800&q=80",
    isPublic: true,
  },
  {
    id: "c6",
    userId: "6",
    title: "Seoul Adventures",
    coverImage: "https://images.unsplash.com/photo-1517154421773-0529f29ea451?auto=format&fit=crop&w=800&q=80",
    isPublic: true,
  },
  {
    id: "c7",
    userId: "7",
    title: "Berlin Finds",
    coverImage: "https://images.unsplash.com/photo-1560969184-10fe8719e047?auto=format&fit=crop&w=800&q=80",
    isPublic: true,
  },
  {
    id: "c8",
    userId: "8",
    title: "Amsterdam Art Scene",
    coverImage: "https://images.unsplash.com/photo-1534070249-34b748a9d18e?auto=format&fit=crop&w=800&q=80",
    isPublic: true,
  },
];

export const places = [
  {
    id: "p1",
    collectionId: "c1",
    userId: "1",
    category: "Food",
    name: "Ichiran Ramen",
    description: "The best solo dining ramen experience. A must-visit!",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80",
    link: "https://en.ichiran.com/",
    rating: 5,
    notes: "Go early to avoid the line. Get the extra chashu.",
    timestamp: "2 hours ago",
  },
  {
    id: "p2",
    collectionId: "c2",
    userId: "1",
    category: "Museum",
    name: "MoMA",
    description: "Always a classic.",
    image: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=800&q=80",
    link: "https://moma.org",
    rating: 4,
    notes: "Free on Fridays!",
    timestamp: "1 day ago",
  },
  {
    id: "p3",
    collectionId: "c3",
    userId: "2",
    category: "Food",
    name: "Café de Flore",
    description: "Iconic spot for people watching.",
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80",
    link: "https://cafedeflore.fr/",
    rating: 4,
    notes: "Hot chocolate is amazing but pricey.",
    timestamp: "3 days ago",
  },
  {
    id: "p4",
    collectionId: "c1",
    userId: "1",
    category: "Other",
    name: "Trunk Hotel",
    description: "Super trendy boutique hotel in Shibuya.",
    image: "https://images.unsplash.com/photo-1752409907212-157e96168590?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBib3V0aXF1ZSUyMGhvdGVsJTIwc2hpYnV5YXxlbnwxfHx8fDE3NzYwMTI5NDB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    link: "https://trunk-hotel.com",
    rating: 5,
    notes: "The lobby bar is a great place to work.",
    timestamp: "1 week ago",
  },
  {
    id: "p5",
    collectionId: "c4",
    userId: "4",
    category: "Sights",
    name: "The Shard",
    description: "Stunning views from the top of London's tallest building.",
    image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80",
    link: "",
    rating: 5,
    notes: "Book sunset tickets for the best experience.",
    timestamp: "3 hours ago",
  },
  {
    id: "p6",
    collectionId: "c5",
    userId: "5",
    category: "Food",
    name: "Cervecería Catalana",
    description: "The best tapas in Barcelona. Hands down.",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80",
    link: "",
    rating: 5,
    notes: "Try the patatas bravas and jamón ibérico.",
    timestamp: "5 hours ago",
  },
  {
    id: "p7",
    collectionId: "c6",
    userId: "6",
    category: "Shops",
    name: "Common Ground",
    description: "Multi-story shopping complex made of shipping containers.",
    image: "https://images.unsplash.com/photo-1601024445121-e5b82f020549?auto=format&fit=crop&w=800&q=80",
    link: "",
    rating: 4,
    notes: "Great rooftop views and unique Korean streetwear brands.",
    timestamp: "8 hours ago",
  },
  {
    id: "p8",
    collectionId: "c7",
    userId: "7",
    category: "Museum",
    name: "East Side Gallery",
    description: "The longest remaining section of the Berlin Wall.",
    image: "https://images.unsplash.com/photo-1599946347371-68eb71b16afc?auto=format&fit=crop&w=800&q=80",
    link: "",
    rating: 5,
    notes: "Free to visit. Best in the morning when it's less crowded.",
    timestamp: "12 hours ago",
  },
  {
    id: "p9",
    collectionId: "c8",
    userId: "8",
    category: "Museum",
    name: "Rijksmuseum",
    description: "Home to masterpieces by Rembrandt and Vermeer.",
    image: "https://images.unsplash.com/photo-1583074021541-ebd1bfc6e4ef?auto=format&fit=crop&w=800&q=80",
    link: "",
    rating: 5,
    notes: "Book tickets online to skip the queue. The gardens are free!",
    timestamp: "1 day ago",
  },
  {
    id: "p10",
    collectionId: "c4",
    userId: "4",
    category: "Food",
    name: "Dishoom",
    description: "Bombay-style cafe with incredible breakfast.",
    image: "https://images.unsplash.com/photo-1517244683847-7456b63c5969?auto=format&fit=crop&w=800&q=80",
    link: "",
    rating: 5,
    notes: "Get the bacon naan roll - you won't regret it.",
    timestamp: "2 days ago",
  },
  {
    id: "p11",
    collectionId: "c5",
    userId: "5",
    category: "Sights",
    name: "Park Güell",
    description: "Gaudí's colorful masterpiece with panoramic city views.",
    image: "https://images.unsplash.com/photo-1560969184-10fe8719e047?auto=format&fit=crop&w=800&q=80",
    link: "",
    rating: 4,
    notes: "Buy tickets in advance. Gets very crowded after 11am.",
    timestamp: "3 days ago",
  },
  {
    id: "p12",
    collectionId: "c6",
    userId: "6",
    category: "Food",
    name: "Gwangjang Market",
    description: "Traditional Korean market with amazing street food.",
    image: "https://images.unsplash.com/photo-1579027989536-b7b1f875659b?auto=format&fit=crop&w=800&q=80",
    link: "",
    rating: 5,
    notes: "Must try: bindaetteok (mung bean pancakes) and mayak gimbap.",
    timestamp: "4 days ago",
  },
  {
    id: "p13",
    collectionId: "c7",
    userId: "7",
    category: "Food",
    name: "Mustafa's Gemüse Kebap",
    description: "Worth the wait for the best döner in Berlin.",
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=800&q=80",
    link: "",
    rating: 5,
    notes: "Lines are long but move fast. Cash only!",
    timestamp: "5 days ago",
  },
  {
    id: "p14",
    collectionId: "c8",
    userId: "8",
    category: "Food",
    name: "De Kas",
    description: "Farm-to-table dining in a beautiful greenhouse.",
    image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=800&q=80",
    link: "",
    rating: 5,
    notes: "Reservations essential. The tasting menu is worth every euro.",
    timestamp: "6 days ago",
  },
  {
    id: "p15",
    collectionId: "c4",
    userId: "4",
    category: "Shops",
    name: "Borough Market",
    description: "Historic food market with artisan producers.",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80",
    link: "",
    rating: 4,
    notes: "Busiest on weekends. Great for lunch and food shopping.",
    timestamp: "1 week ago",
  },
  {
    id: "p16",
    collectionId: "c5",
    userId: "5",
    category: "Shops",
    name: "La Boqueria",
    description: "Iconic public market on La Rambla.",
    image: "https://images.unsplash.com/photo-1583258292688-d0213dc5a3a8?auto=format&fit=crop&w=800&q=80",
    link: "",
    rating: 4,
    notes: "Go early to avoid tourist crowds. Fresh fruit smoothies are amazing.",
    timestamp: "1 week ago",
  },
  {
    id: "p17",
    collectionId: "c6",
    userId: "6",
    category: "Sights",
    name: "Bukchon Hanok Village",
    description: "Traditional Korean houses nestled in modern Seoul.",
    image: "https://images.unsplash.com/photo-1517154421773-0529f29ea451?auto=format&fit=crop&w=800&q=80",
    link: "",
    rating: 5,
    notes: "Respect the residents - people actually live here!",
    timestamp: "2 weeks ago",
  },
  {
    id: "p18",
    collectionId: "c7",
    userId: "7",
    category: "Sights",
    name: "Brandenburg Gate",
    description: "Berlin's most famous landmark.",
    image: "https://images.unsplash.com/photo-1599946347371-68eb71b16afc?auto=format&fit=crop&w=800&q=80",
    link: "",
    rating: 4,
    notes: "Beautiful at night when it's lit up. Free to visit anytime.",
    timestamp: "2 weeks ago",
  },
];

export const postDetailStreamPlaces = [
  {
    id: "pds1",
    collectionId: "c3",
    userId: "2",
    category: "Hidden",
    name: "Carrer del Bisbe",
    description: "Stumbled upon this beautiful narrow street. Architecture is breathtaking.",
    image: "https://images.unsplash.com/photo-1641161995144-9bf2f46e4b20?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYXJjZWxvbmElMjBzdHJlZXR8ZW58MXx8fHwxNzc2MTYzODY1fDA&ixlib=rb-4.1.0&q=80&w=1080",
    link: "",
    rating: 5,
    notes: "Get here early in the morning before the crowds.",
    timestamp: "2 hours ago",
  },
  {
    id: "pds2",
    collectionId: "c2",
    userId: "1",
    category: "Hidden",
    name: "The Fortune of War",
    description: "One of the oldest pubs in the city. Great atmosphere.",
    image: "https://images.unsplash.com/photo-1668420460695-768331592e92?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzeWRuZXklMjBwdWJ8ZW58MXx8fHwxNzc2MTYzODY1fDA&ixlib=rb-4.1.0&q=80&w=1080",
    link: "",
    rating: 4,
    notes: "Live music on weekends is fantastic.",
    timestamp: "1 day ago",
  },
  {
    id: "pds3",
    collectionId: "c1",
    userId: "2",
    category: "Hidden",
    name: "Kaffee Mitte",
    description: "Quiet place to grab a coffee and read a book.",
    image: "https://images.unsplash.com/photo-1632996130498-f9b7f5ae2e63?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiZXJsaW4lMjBjYWZlfGVufDF8fHx8MTc3NjE2Mzg2NXww&ixlib=rb-4.1.0&q=80&w=1080",
    link: "",
    rating: 5,
    notes: "Their matcha latte is top notch.",
    timestamp: "5 days ago",
  },
];

export const savedItems = [
  { id: "s1", type: "place", placeId: "p3" },
  { id: "s2", type: "collection", collectionId: "c3" },
];

export const inspoBoards = [
  {
    id: "i1",
    userId: "1",
    title: "All",
    coverImage: "https://images.unsplash.com/photo-1518098268026-4e89f1a2cd8e?auto=format&fit=crop&w=800&q=80",
    isDefault: true,
  },
  {
    id: "i2",
    userId: "1",
    title: "Summer in Italy",
    coverImage: "https://images.unsplash.com/photo-1583844056361-4418a8f2a985?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhbWFsZmklMjBjb2FzdCUyMGl0YWx5fGVufDF8fHx8MTc3NjAxMjk0MHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    isDefault: false,
  },
];

export const inspoPlaces = [
  {
    id: "ip1",
    inspoBoardId: "i1",
    userId: "1",
    category: "Food",
    name: "Da Enzo al 29",
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80",
    timestamp: "1 week ago",
    notes: "Get the cacio e pepe, it's amazing!",
  },
  {
    id: "ip2",
    inspoBoardId: "i2",
    userId: "1",
    category: "Sights",
    name: "Amalfi Coast",
    image: "https://images.unsplash.com/photo-1612698093158-e07ac200d44e?auto=format&fit=crop&w=800&q=80",
    timestamp: "2 weeks ago",
    notes: "Bring sunscreen and comfortable walking shoes.",
  },
];
